[formatter.taplo]
command  = "taplo"
excludes = []
includes = ["*.toml", ".cargo/config.toml"]
options  = ["fmt", "-o", "align_entries=true", "-o", "reorder_keys=true"]

[formatter.prettier]
command  = "prettier"
excludes = ["*/sources.json"]
includes = ["*.json", "*.md", "*.yaml", "*.yml", "*.css"]
options  = ["--write"]
